# Summarize online of all servers
# If enabled, servers specified in servers will be ignored
sum-all: false

# Summarize maximum online
sum-max-online: true

# Servers from which online will be summarized
servers:
 - "zeqa"
 - "nethergames"